#!/usr/bin/env bash
set -e

pip install allensdk==2.14.1 --ignore-installed ruamel.yaml

pip install jinja2==3.0.1
pip install nbconvert==6.4.4 # started adding below here
pip install scikit-learn
pip install matplotlib==3.7.2
pip install statsmodels==0.13.2
pip install plotly